services:
  server:
    env_file: ".env"
    build:
      context: "cr_autos"
    volumes:
      - car_images:/app/car_images
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PG_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s

volumes:
  car_images:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/cr_autos/car_images"

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/pg"
