# Generated by Django 5.0.4 on 2024-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='car_image',
            field=models.FileField(default='', upload_to='car_images'),
            preserve_default=False,
        ),
    ]
